/**
 * DynamicVisual — renders any visualization type generated by the AI.
 * 
 * This is NOT an editor. It's a read-only renderer that displays whatever
 * the AI decides is helpful for the user's thinking process.
 */
import React from 'react';
import { Card, Tag, Table, Statistic, Row, Col, Typography } from 'antd';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import ReactFlow, { Background, Controls, MarkerType } from 'reactflow';
import 'reactflow/dist/style.css';

const COLORS = ['#1890ff', '#52c41a', '#faad14', '#f5222d', '#722ed1', '#13c2c2', '#eb2f96', '#fa8c16'];

interface VisualProps {
  type: string;
  title: string;
  data: any;
  description?: string;
}

export default function DynamicVisual({ type, title, data, description }: VisualProps) {
  return (
    <Card
      size="small"
      title={<><Tag color="purple">{type}</Tag> {title}</>}
      style={{ marginBottom: 12 }}
    >
      {description && <Typography.Text type="secondary" style={{ display: 'block', marginBottom: 8, fontSize: 12 }}>{description}</Typography.Text>}
      {renderVisual(type, data)}
    </Card>
  );
}

function renderVisual(type: string, data: any) {
  switch (type) {
    case 'mindmap':
    case 'tree':
      return <TreeVisual data={data} />;
    case 'flowchart':
      return <FlowVisual data={data} />;
    case 'network':
      return <NetworkVisual data={data} />;
    case 'timeline':
      return <TimelineVisual data={data} />;
    case 'bar_chart':
      return <BarChartVisual data={data} />;
    case 'pie_chart':
      return <PieChartVisual data={data} />;
    case 'table':
      return <TableVisual data={data} />;
    case 'metric_cards':
      return <MetricCardsVisual data={data} />;
    case 'decision_tree':
      return <TreeVisual data={data} />;
    default:
      return <pre style={{ fontSize: 11, maxHeight: 200, overflow: 'auto' }}>{JSON.stringify(data, null, 2)}</pre>;
  }
}

// ── Tree / Mindmap ──
function TreeVisual({ data }: { data: any }) {
  const renderNode = (node: any, depth = 0): React.ReactNode => {
    const indent = depth * 20;
    const color = COLORS[depth % COLORS.length];
    return (
      <div key={node.label || node.center || node.question} style={{ marginLeft: indent }}>
        <div style={{ padding: '4px 8px', margin: '2px 0', borderLeft: depth > 0 ? `3px solid ${color}` : 'none', background: depth === 0 ? '#f0f5ff' : 'transparent', borderRadius: 4, fontWeight: depth === 0 ? 600 : 400 }}>
          {node.label || node.center || node.question}
          {node.value !== undefined && <Tag style={{ marginLeft: 8 }}>{node.value}</Tag>}
        </div>
        {(node.children || node.branches || node.options || []).map((child: any) => renderNode(child, depth + 1))}
      </div>
    );
  };
  return <div style={{ padding: 8 }}>{renderNode(data)}</div>;
}

// ── Flowchart / Network (via ReactFlow, read-only) ──
function FlowVisual({ data }: { data: any }) {
  const nodes = (data.nodes || []).map((n: any, i: number) => ({
    id: n.id || `n${i}`,
    position: { x: (i % 3) * 180 + 50, y: Math.floor(i / 3) * 100 + 30 },
    data: { label: n.label || n.id },
    style: { borderRadius: 8, border: '2px solid #1890ff', fontSize: 12, padding: 8 },
  }));
  const edges = (data.edges || []).map((e: any, i: number) => ({
    id: `e${i}`,
    source: e.source,
    target: e.target,
    label: e.label || '',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
  }));
  return (
    <div style={{ height: Math.max(200, Math.ceil(nodes.length / 3) * 120 + 60) }}>
      <ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} nodesConnectable={false} elementsSelectable={false}>
        <Background />
      </ReactFlow>
    </div>
  );
}

function NetworkVisual({ data }: { data: any }) {
  return <FlowVisual data={{ nodes: data.nodes, edges: (data.links || []).map((l: any) => ({ source: l.source, target: l.target, label: l.label })) }} />;
}

// ── Timeline ──
function TimelineVisual({ data }: { data: any }) {
  return (
    <div style={{ padding: '8px 0' }}>
      {(data.events || []).map((ev: any, i: number) => (
        <div key={i} style={{ display: 'flex', gap: 12, marginBottom: 8, alignItems: 'flex-start' }}>
          <div style={{ minWidth: 90, color: '#1890ff', fontWeight: 600, fontSize: 12 }}>{ev.date}</div>
          <div style={{ width: 8, height: 8, borderRadius: '50%', background: COLORS[i % COLORS.length], marginTop: 4, flexShrink: 0 }} />
          <div>
            <div style={{ fontWeight: 500 }}>{ev.title}</div>
            {ev.description && <div style={{ fontSize: 12, color: '#888' }}>{ev.description}</div>}
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Bar Chart ──
function BarChartVisual({ data }: { data: any }) {
  const chartData = (data.labels || []).map((label: string, i: number) => {
    const point: any = { name: label };
    (data.datasets || []).forEach((ds: any) => { point[ds.label] = ds.values?.[i] || 0; });
    return point;
  });
  const datasetLabels = (data.datasets || []).map((ds: any) => ds.label);
  return (
    <ResponsiveContainer width="100%" height={220}>
      <BarChart data={chartData}><XAxis dataKey="name" fontSize={11} /><YAxis fontSize={11} /><Tooltip />
        {datasetLabels.map((label: string, i: number) => <Bar key={label} dataKey={label} fill={COLORS[i % COLORS.length]} />)}
        <Legend />
      </BarChart>
    </ResponsiveContainer>
  );
}

// ── Pie Chart ──
function PieChartVisual({ data }: { data: any }) {
  const segments = data.segments || [];
  return (
    <ResponsiveContainer width="100%" height={220}>
      <PieChart><Pie data={segments} dataKey="value" nameKey="label" cx="50%" cy="50%" outerRadius={80} label>
        {segments.map((_: any, i: number) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
      </Pie><Tooltip /><Legend /></PieChart>
    </ResponsiveContainer>
  );
}

// ── Table ──
function TableVisual({ data }: { data: any }) {
  const columns = (data.columns || []).map((col: string) => ({ title: col, dataIndex: col, key: col }));
  const rows = (data.rows || []).map((row: any[], i: number) => {
    const obj: any = { key: i };
    (data.columns || []).forEach((col: string, j: number) => { obj[col] = row[j]; });
    return obj;
  });
  return <Table dataSource={rows} columns={columns} size="small" pagination={false} scroll={{ y: 200 }} />;
}

// ── Metric Cards ──
function MetricCardsVisual({ data }: { data: any }) {
  return (
    <Row gutter={12}>
      {(data.cards || []).map((card: any, i: number) => (
        <Col key={i} span={Math.max(6, Math.floor(24 / (data.cards || []).length))}>
          <Card size="small">
            <Statistic title={card.title} value={card.value} suffix={card.unit || ''} valueStyle={{ color: COLORS[i % COLORS.length] }} />
            {card.change && <div style={{ fontSize: 11, color: card.change.startsWith('+') || card.change.startsWith('↑') ? '#52c41a' : '#f5222d' }}>{card.change}</div>}
          </Card>
        </Col>
      ))}
    </Row>
  );
}
